name: 'setup-sst-v3'
description: 'Setup SST with caching enabled'
author: 'Bruno Leite'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'zap'
  color: 'blue'

# Define your inputs here.
inputs:
  package-lock:
    description: 'package-lock.json file location'
    default: 'package-lock.json'
  sst-config:
    description: 'sst.config.ts file location'
    default: 'sst.config.ts'

runs:
  using: node20
  main: dist/index.js
