name: 'setup-sst-v3'
description: 'Setup SST with caching enabled'
author: 'Bruno Leite'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'zap'
  color: 'blue'

# Define your inputs here.
inputs:
  sst-folder:
    description: 'SST folder location'
    default: './'
  platform-only:
    description:
      "Only caches the SST platform files on '.sst/platform'. Useful for linting
      runs that will not deploy."
    default: 'false'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
