/**
 * Tests for lockfile detection and parsing.
 *
 * The fixtures under `__test_environments__` are generated by the real package
 * managers, so these assert against genuine lockfile formats rather than
 * hand-written approximations.
 */

import * as path from 'path'
import {
  detectPackageManager,
  findLockfile,
  parseBunLockfile,
  parseNpmLockfile,
  parsePnpmLockfile,
  parseYarnLockfile,
  readLockfile
} from '../src/lockfile'

const fixtures = path.resolve(__dirname, '../__test_environments__')
const hashStub = (): Promise<string> => Promise.resolve('deadbeef')

describe('detectPackageManager', () => {
  it.each([
    ['package-lock.json', 'npm'],
    ['npm-shrinkwrap.json', 'npm'],
    ['bun.lock', 'bun'],
    ['bun.lockb', 'bun'],
    ['pnpm-lock.yaml', 'pnpm'],
    ['yarn.lock', 'yarn']
  ])('detects %s as %s', (file, expected) => {
    expect(detectPackageManager(`/repo/${file}`)).toBe(expected)
  })

  it('returns null for an unrecognised lockfile', () => {
    expect(detectPackageManager('/repo/Cargo.lock')).toBeNull()
  })
})

describe('findLockfile', () => {
  it('finds the npm lockfile in a directory', () => {
    const found = findLockfile(path.join(fixtures, 'with-npm'))
    expect(found).toBe(path.join(fixtures, 'with-npm', 'package-lock.json'))
  })

  it('finds a pnpm lockfile', () => {
    expect(findLockfile(path.join(fixtures, 'with-pnpm'))).toBe(
      path.join(fixtures, 'with-pnpm', 'pnpm-lock.yaml')
    )
  })

  it('returns null when a directory has no lockfile', () => {
    expect(findLockfile(fixtures)).toBeNull()
  })
})

describe('parseNpmLockfile', () => {
  it('reads the version from a lockfileVersion 3 lockfile', () => {
    const contents = JSON.stringify({
      lockfileVersion: 3,
      packages: { 'node_modules/sst': { version: '3.19.3' } }
    })
    expect(parseNpmLockfile(contents)).toBe('3.19.3')
  })

  it('reads the version from a lockfileVersion 1 lockfile', () => {
    const contents = JSON.stringify({
      lockfileVersion: 1,
      dependencies: { sst: { version: '3.17.0' } }
    })
    expect(parseNpmLockfile(contents)).toBe('3.17.0')
  })

  it('throws when SST is absent', () => {
    expect(() => parseNpmLockfile('{"packages":{}}')).toThrow(
      /Could not find the 'sst' package/
    )
  })

  it('throws a helpful error for malformed JSON', () => {
    expect(() => parseNpmLockfile('not json')).toThrow(/Could not parse/)
  })
})

describe('parseBunLockfile', () => {
  it('reads the version from the resolution string', () => {
    const contents = `{
      // bun.lock is JSONC, so comments are legal here
      "lockfileVersion": 1,
      "packages": {
        "sst": ["sst@3.19.3", "", { "bin": { "sst": "bin/sst.mjs" } }, "sha512-abc"],
      }
    }`
    expect(parseBunLockfile(contents)).toBe('3.19.3')
  })

  it('handles scoped-style keys under node_modules', () => {
    const contents = `{"packages":{"node_modules/sst":["sst@3.18.1","",{},""]}}`
    expect(parseBunLockfile(contents)).toBe('3.18.1')
  })

  it('throws when SST is absent', () => {
    expect(() => parseBunLockfile('{"packages":{}}')).toThrow(
      /Could not find the 'sst' package/
    )
  })

  it('throws when the file is binary rather than text', () => {
    expect(() => parseBunLockfile('\u0000\u0001binary')).toThrow(
      /Could not parse `bun.lock`/
    )
  })
})

describe('parsePnpmLockfile', () => {
  it('reads the resolved version of a direct dependency', () => {
    const contents = [
      "lockfileVersion: '9.0'",
      '',
      'importers:',
      '',
      '  .:',
      '    dependencies:',
      '      sst:',
      '        specifier: 3.19.3',
      '        version: 3.19.3',
      ''
    ].join('\n')
    expect(parsePnpmLockfile(contents)).toBe('3.19.3')
  })

  it('falls back to the package graph key', () => {
    const contents = [
      'packages:',
      '',
      '  sst@3.16.4:',
      '    resolution: {}'
    ].join('\n')
    expect(parsePnpmLockfile(contents)).toBe('3.16.4')
  })

  it('throws when SST is absent', () => {
    expect(() => parsePnpmLockfile('packages:\n  foo@1.0.0:\n')).toThrow(
      /Could not find the 'sst' package/
    )
  })
})

describe('parseYarnLockfile', () => {
  it('reads a Yarn Classic entry', () => {
    const contents = [
      '# yarn lockfile v1',
      '',
      'sst@3.19.3:',
      '  version "3.19.3"',
      '  resolved "https://registry.yarnpkg.com/sst/-/sst-3.19.3.tgz"',
      ''
    ].join('\n')
    expect(parseYarnLockfile(contents)).toBe('3.19.3')
  })

  it('reads a Yarn Berry entry', () => {
    const contents = [
      '"sst@npm:^3.19.0":',
      '  version: 3.19.3',
      '  resolution: "sst@npm:3.19.3"',
      '  languageName: node',
      ''
    ].join('\n')
    expect(parseYarnLockfile(contents)).toBe('3.19.3')
  })

  it('reads an entry whose block lists several descriptors', () => {
    const contents = [
      '"sst@npm:^3.18.0, sst@npm:^3.19.0":',
      '  version: 3.19.3',
      '  resolution: "sst@npm:3.19.3"',
      ''
    ].join('\n')
    expect(parseYarnLockfile(contents)).toBe('3.19.3')
  })

  it('does not confuse a similarly named package for sst', () => {
    const contents = [
      'sst-linux-x64@3.19.3:',
      '  version "3.19.3"',
      '',
      'sst@3.11.0:',
      '  version "3.11.0"',
      ''
    ].join('\n')
    expect(parseYarnLockfile(contents)).toBe('3.11.0')
  })

  it('throws when SST is absent', () => {
    expect(() => parseYarnLockfile('foo@1.0.0:\n  version "1.0.0"\n')).toThrow(
      /Could not find the 'sst' package/
    )
  })
})

describe('readLockfile', () => {
  it('reads a real npm lockfile fixture', async () => {
    const result = await readLockfile(
      path.join(fixtures, 'with-npm', 'package-lock.json'),
      hashStub
    )
    expect(result.packageManager).toBe('npm')
    expect(result.runCommand).toBe('npx')
    expect(result.isHash).toBe(false)
    expect(result.sstVersion).toMatch(/^3\./)
  })

  it('reads a real bun text lockfile fixture', async () => {
    const result = await readLockfile(
      path.join(fixtures, 'with-bun-text', 'bun.lock'),
      hashStub
    )
    expect(result.packageManager).toBe('bun')
    expect(result.runCommand).toBe('bunx')
    expect(result.sstVersion).toBe('3.19.3')
    expect(result.isHash).toBe(false)
  })

  it('reads a real pnpm lockfile fixture', async () => {
    const result = await readLockfile(
      path.join(fixtures, 'with-pnpm', 'pnpm-lock.yaml'),
      hashStub
    )
    expect(result.packageManager).toBe('pnpm')
    expect(result.runCommand).toBe('pnpm')
    expect(result.sstVersion).toBe('3.19.3')
  })

  it('reads a real yarn lockfile fixture', async () => {
    const result = await readLockfile(
      path.join(fixtures, 'with-yarn', 'yarn.lock'),
      hashStub
    )
    expect(result.packageManager).toBe('yarn')
    expect(result.runCommand).toBe('yarn')
    expect(result.sstVersion).toBe('3.19.3')
  })

  it('hashes a binary bun lockfile instead of parsing it', async () => {
    const result = await readLockfile(
      path.join(fixtures, 'with-bun', 'bun.lockb'),
      hashStub
    )
    expect(result.packageManager).toBe('bun')
    expect(result.sstVersion).toBe('deadbeef')
    expect(result.isHash).toBe(true)
  })

  it('throws for an unsupported lockfile name', async () => {
    await expect(readLockfile('/repo/Cargo.lock', hashStub)).rejects.toThrow(
      /Unsupported lockfile/
    )
  })

  it('throws when the lockfile does not exist', async () => {
    await expect(
      readLockfile('/nope/package-lock.json', hashStub)
    ).rejects.toThrow(/Lockfile not found/)
  })
})
